# Generated by Django 4.0.4 on 2022-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'My custom message'}, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
