# Generated by Django 4.0.4 on 2022-05-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_is_guest_delete_mealclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_price',
            field=models.IntegerField(default=0),
        ),
    ]
