# Generated by Django 4.0.4 on 2022-05-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_meal_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(unique=True),
        ),
    ]
