# Generated by Django 4.0.4 on 2022-05-20 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_description',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2022, 5, 20)),
        ),
    ]
