# Generated by Django 4.0.4 on 2022-05-24 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_meal_meal_description_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2022, 5, 24)),
        ),
    ]
