# Generated by Django 4.0.4 on 2022-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_penaltyCount',
            field=models.IntegerField(default=0),
        ),
    ]
